# Makefile generated by BNFC.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean test

# Default goal.

all : latte

# Rules for building the parser.

Latte/Abs.hs Latte/Lex.x Latte/Par.y Latte/Print.hs Latte/Test.hs : Latte.cf
	bnfc --haskell -d --functor Latte.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

latte : Latte/Abs.hs Latte/Lex.hs Latte/Par.hs Latte/Main.hs Latte/RunTime.hs  Latte/Shows.hs Latte/StaticAnalysis.hs Latte/TypeChecking.hs Latte/Error.hs Latte/Types.hs
	${GHC} Latte/Main.hs --make -o latte

# Rules for cleaning generated files.

clean :
	-rm -f Latte/*.hi Latte/*.o Latte/*.log Latte/*.aux Latte/*.dvi ./latte Latte/Abs.hs Latte/Doc.txt Latte/ErrM.hs Latte/Lex.hs Latte/Lex.x Latte/Par.hs Latte/Par.info Latte/Par.y Latte/Print.hs Latte/Skel.hs Latte/Test.hs

test : latte
	./test.sh

# EOF
